### ISSUE TITLE
Loaded my old save after getting latest mod/factorio version and ran into this

### ISSUE THREAD

**Issue by martsrzx91** [refulgence/quantum-fabrication#11]
Hi again >_> 

![image](https://github.com/user-attachments/assets/6b078099-0144-404c-976d-360528966345)

**Comment by refulgence** [comment]
Please upload your save, because I have no idea what could cause it.

**Comment by martsrzx91** [comment]
[mod-list.json](https://github.com/user-attachments/files/17821808/mod-list.json)

Where do i upload it to?

![image](https://github.com/user-attachments/assets/0ecd7f76-31e5-436e-b3e7-774787761dc7)

**Comment by martsrzx91** [comment]
https://easyupload.io/4az9kz

**Comment by refulgence** [comment]
Thanks, the save helped.

Fixed in 2.3.1

**Comment by martsrzx91** [comment]
;)
