### ISSUE TITLE
Iz me again ;(

### ISSUE THREAD

**Issue by martsrzx91** [refulgence/quantum-fabrication#12]
I messed one planet up so i tried to delete its surface via editor and save crashed with this 
![image](https://github.com/user-attachments/assets/63033e08-2e75-478a-9bd6-e83e83b5ae6b)

Heres me finding weird ways how to break stuff or some bizarro scenarios :D

**Comment by refulgence** [comment]
And to think that this function's entire purpose was to prevent this exact crash from happening. Wow. 

Fixed in 2.3.2.

**Comment by martsrzx91** [comment]
Sry for making you do extra work on the regular >_>

**Comment by refulgence** [comment]
Nah, it's okay, these bugs shouldn't had existed in the first place.

**Comment by martsrzx91** [comment]
Happy to help then by breaking stuff :D
