### ISSUE TITLE
Hello there :)

### ISSUE THREAD

**Issue by martsrzx91** [refulgence/quantum-fabrication#13]
Tried to create a new map file and it took quite the time and later crashed without loading me into created map

![image](https://github.com/user-attachments/assets/db3bdd4f-09d8-4f5a-9352-ba09b60af164)
[mod-list.json](https://github.com/user-attachments/files/17875991/mod-list.json)
New mod i am trying to get running is StarsWithSakura, could be related
https://mods.factorio.com/mod/StarsWithSakura

**Comment by refulgence** [comment]
That mod has recipes that require their only product (like, Loader V requiring Loader V x2 instead of Loader IV x2), so my mod gets stuck in an infinite loop trying to process them.

I've fixed it from my side, so the map will load. But you should also report the core cause to that mod's author.

**Comment by Deadexow** [comment]
Yes，infinite loop is a normal problem when the other mods , like [Reverse Factory](https://mods.factorio.com/mod/reverse-factory?from=search)，fix my entities.

**Comment by martsrzx91** [comment]
I just want everything to play nice together :)

**Comment by Deadexow** [comment]
I am glad to receive your reply. My mod has poor compatibility due to the extensive traversal and calculations involved. I plan to develop a completely new gameplay experience, much like exploring space. My goal is to combine elements of Factorio (Alien Factory) with RPG, RTS, and ACT genres.
&nbsp;


????????
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月23日(星期六) 下午4:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [refulgence/quantum-fabrication] Hello there :) (Issue #13)














 
I just want everything to play nice together :)

**Comment by martsrzx91** [comment]
No worries, all I'm just saying is try to fix stuff, if you cant then it is all good and i will just have to choose one or the other ;)

**Comment by Deadexow** [comment]
Yes, I will gradually update this mod. My vision is for the mod to include a financial system and universe mechanics similar to those in Stellaris, such as trade wars and financial battles. I also want to incorporate a city-state system like in Mount &amp; Blade II: Bannerlord, various flashy skill mechanisms similar to those in MOBA games, and intricate equipment systems like in Dungeons. By then, it won't be me making my mod compatible with others; it will be other mods trying to be compatible with mine.




????????
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "refulgence/quantum-fabrication"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月23日(星期六) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [refulgence/quantum-fabrication] Hello there :) (Issue #13)





 
No worries, all I'm just saying is try to fix stuff, if you cant then it is all good and i will just have to choose one or the other ;)

**Comment by martsrzx91** [comment]
Sounds cool, cant wait to see it ;)
