### ISSUE TITLE
Yo, Long time no see :D Save crash when upgrading building and mod tried to combine entities

### ISSUE THREAD

**Issue by martsrzx91** [refulgence/quantum-fabrication#15]
![image](https://github.com/user-attachments/assets/c9b0d45c-6bf7-4bef-a571-3098f2b818da)

**Comment by refulgence** [comment]
Seems like my mod just raised the event, the crash happened because Modular Buildings Redux couldn't find a prototype. Gonna assume you are using another mod that adds upgradable steam engines, but Modular Buildings can only work with upgradable steam engines from Bob's mods.

**Comment by martsrzx91** [comment]
The mod i have which gives better building tiers is https://mods.factorio.com/mod/PHI-CL?from=search
