### ISSUE TITLE
Mods not playing nice together

### ISSUE THREAD

**Issue by martsrzx91** [refulgence/quantum-fabrication#5]
As soon as i click on processing in that quantum fabricator window or any other tab aside from first tab save crashes with this, any idea how to fix?

![Untitled](https://github.com/user-attachments/assets/6b964341-06a3-42ca-bc7b-1b9bf8851326)

**Comment by refulgence** [comment]
I couldn't reproduce it, but I think I fixed it: we both used the same name for a GUI element, so I removed mine. Please check if the issue persists in the new version.

**Comment by martsrzx91** [comment]
Wow, a quick turnaroud, the issue seems to be fixed no more save crash ;)
![image](https://github.com/user-attachments/assets/68d463e7-0bf5-4421-a47f-5ac218a4a62b)
