### ISSUE TITLE
Save crashed while using environment deconstruct on fulgora

### ISSUE THREAD

**Issue by martsrzx91** [refulgence/quantum-fabrication#7]
![image](https://github.com/user-attachments/assets/18f6bc03-0b1c-4833-a12e-6b623778c840)

**Comment by martsrzx91** [comment]
Another one, was just chilling reading stuff ingame

![image](https://github.com/user-attachments/assets/2ab038b6-a82a-4538-b270-36bf6babac7e)

**Comment by refulgence** [comment]
Thanks for the report, will fix today.

**Comment by martsrzx91** [comment]
Nope that aint it 
![image](https://github.com/user-attachments/assets/a38631d9-5d14-4e2e-9b7a-039fd23e4088)

**Comment by martsrzx91** [comment]
With what is it having issue, what should i not do or avoid doing?

**Comment by refulgence** [comment]
![image](https://github.com/user-attachments/assets/297ce864-b130-4b3c-8b2d-d0c3aea7f44a)
GUI -> Preferences -> Uncheck "Automatically recheck for lost item request proxies" and it should stop crashing, theoretically.

Something in your game deleted a surface with a machine that was requesting modules. Maybe you have some kind of a blueprint designer mod, or maybe Factorissimo.

**Comment by martsrzx91** [comment]
Couldnt find blueprint mod, mby i have, but yes before it started crashing i was planning to build space plaform where i pasted bp and ultimately decided against it and used ctrl+z for undo and removed space platform and crashes started appearing, and no factorissimo, will try to fix with ur reccomendation

**Comment by martsrzx91** [comment]
Worked like a charm, crashes stopped ;) Ur awesome my dude ^_^

**Comment by martsrzx91** [comment]
Another different one while traveling on space platform to Nauvis

![image](https://github.com/user-attachments/assets/7bfce3e8-1b2c-4175-971a-abb05b84dd89)

**Comment by refulgence** [comment]
It's the same bug, just caused by a different thing. I'll fix it soon.

**Comment by martsrzx91** [comment]
;) for the time being then im disabling the mod

**Comment by refulgence** [comment]
Alright, should be fixed in 2.1.1.
